name: Process CSV

on:
  push:
    paths:
      - 'data/*.csv'

permissions:
  contents: write

jobs:
  process_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas xlsxwriter openpyxl

      - name: Run python scripts/process_ilims.py
        run: |
          python scripts/process_ilims.py

      - name: Rename output file with date and time (IST)
        run: |
          TS=$(TZ=Asia/Kolkata date +'%Y-%m-%d_%H-%M-%S')
          mv output/ilims-output.xlsx output/ilims-output-$TS.xlsx

      - name: Commit output file to repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add output/
          git commit -m "Add ILIMS output ($TS)" || echo "No changes to commit"
          git push

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ilims-output
          path: output/

      - name: Delete processed CSV files
        run: |
          rm -f data/*.csv

          git add data/
          git commit -m "Remove processed CSV files" || echo "No CSV files to delete"
          git push
