name: Process CSV

on:
  push:
    paths:
      - 'data/*.csv'

permissions:
  contents: write   

jobs:
  process_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas xlsxwriter openpyxl

      - name: Run python scripts/process_ilims.py
        run: |
          python scripts/process_ilims.py

      - name: Rename output file with current date
        run: |
          DATE=$(date +'%Y-%m-%d')
          mv output/ilims-output.xlsx output/ilims-output-$DATE.xlsx

      - name: Commit output file to repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add output/
          git commit -m "Add ILIMS output ($(date +'%Y-%m-%d'))" || echo "No changes"
          git push

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ilims-output
          path: output/
